CLASS zcl_get_uuid_x16 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    class-METHODS
        generate_uuid_x16
            RETURNING VALUE(uuidx16) type sysuuid_x16.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.



CLASS ZCL_GET_UUID_X16 IMPLEMENTATION.
ENDCLASS.
